// <auto-generated />
using System;
using EcommerceLifestyle.DAL.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcommerceLifestyle.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EcommerceLifestyle.DAL.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("EcommerceLifestyle.DAL.Entities.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("int");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("int");

                    b.Property<int?>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.HasIndex("VendorId");

                    b.ToTable("Inventory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = "pw-001",
                            QuantityAvailable = 50,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 2,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = "pw-002",
                            QuantityAvailable = 50,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 3,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = "pw-003",
                            QuantityAvailable = 50,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 4,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = "pw-004",
                            QuantityAvailable = 50,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 5,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = "pw-005",
                            QuantityAvailable = 50,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 6,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = "pw-006",
                            QuantityAvailable = 50,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 7,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = "ew-001",
                            QuantityAvailable = 50,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 8,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = "ew-002",
                            QuantityAvailable = 50,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 9,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = "ew-003",
                            QuantityAvailable = 50,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 10,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = "ew-004",
                            QuantityAvailable = 50,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 11,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = "ew-005",
                            QuantityAvailable = 50,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 12,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = "ew-006",
                            QuantityAvailable = 50,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 13,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = "fm-001",
                            QuantityAvailable = 50,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 14,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = "fm-002",
                            QuantityAvailable = 50,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 15,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = "fm-003",
                            QuantityAvailable = 50,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 16,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = "fm-004",
                            QuantityAvailable = 50,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 17,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = "fm-005",
                            QuantityAvailable = 50,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 18,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = "fm-006",
                            QuantityAvailable = 50,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 19,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = "cs-001",
                            QuantityAvailable = 50,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 20,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = "cs-002",
                            QuantityAvailable = 50,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 21,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = "cs-003",
                            QuantityAvailable = 50,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 22,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = "cs-004",
                            QuantityAvailable = 50,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 23,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = "cs-005",
                            QuantityAvailable = 50,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 24,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = "cs-006",
                            QuantityAvailable = 50,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 25,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = "bs-001",
                            QuantityAvailable = 50,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 26,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = "bs-002",
                            QuantityAvailable = 50,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 27,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = "bs-003",
                            QuantityAvailable = 50,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 28,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = "bs-004",
                            QuantityAvailable = 50,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 29,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = "bs-005",
                            QuantityAvailable = 50,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 30,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = "bs-006",
                            QuantityAvailable = 50,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 31,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = "fk-001",
                            QuantityAvailable = 50,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 32,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = "fk-002",
                            QuantityAvailable = 50,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 33,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = "fk-003",
                            QuantityAvailable = 50,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 34,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = "fk-004",
                            QuantityAvailable = 50,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 35,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = "fk-005",
                            QuantityAvailable = 50,
                            ReorderLevel = 5
                        },
                        new
                        {
                            Id = 36,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = "fk-006",
                            QuantityAvailable = 50,
                            ReorderLevel = 5
                        });
                });

            modelBuilder.Entity("EcommerceLifestyle.DAL.Entities.Log", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("RequestPath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("EcommerceLifestyle.DAL.Entities.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ShipCity")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("ShipCountry")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("ShipFirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("ShipLastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("ShipLine1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ShipState")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("ShipZip")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("Shipping")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EcommerceLifestyle.DAL.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("EcommerceLifestyle.DAL.Entities.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Badge")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("InStock")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<decimal?>("OriginalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(2,1)");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("Subcategory")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<int?>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Subcategory");

                    b.HasIndex("VendorId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "pw-001",
                            Badge = "Sale",
                            Description = "Make a grand entrance with this midnight-black sequin blazer. Slim-fit cut with satin lapels, perfect for club nights and festive dinners. Pairs beautifully with black trousers or dark jeans.",
                            Image = "https://images.unsplash.com/photo-1594938298603-c8148c4b4ae1?w=600&h=700&fit=crop",
                            InStock = true,
                            Name = "Midnight Sequin Blazer",
                            OriginalPrice = 4999m,
                            Price = 3499m,
                            Rating = 4.7m,
                            ReviewCount = 312,
                            Slug = "midnight-sequin-blazer",
                            Subcategory = "party-wear"
                        },
                        new
                        {
                            Id = "pw-002",
                            Badge = "Hot",
                            Description = "A stunning fusion of contemporary style and traditional Indian craftsmanship. Rich brocade Nehru jacket paired with slim churidar trousers. Ideal for cocktail parties, receptions, and festive occasions.",
                            Image = "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&h=700&fit=crop",
                            InStock = true,
                            Name = "Indo-Western Nehru Jacket Set",
                            OriginalPrice = 5500m,
                            Price = 4199m,
                            Rating = 4.8m,
                            ReviewCount = 489,
                            Slug = "indo-western-nehru-jacket-set",
                            Subcategory = "party-wear"
                        },
                        new
                        {
                            Id = "pw-003",
                            Badge = "Premium",
                            Description = "Luxurious deep-burgundy velvet tuxedo that commands attention. Shawl lapel design with satin trim and matching trousers. The ultimate choice for gala dinners and black-tie events.",
                            Image = "https://images.unsplash.com/photo-1617127365659-c47fa9d30294?w=600&h=700&fit=crop",
                            InStock = true,
                            Name = "Velvet Tuxedo Suit",
                            OriginalPrice = 12000m,
                            Price = 8999m,
                            Rating = 4.9m,
                            ReviewCount = 201,
                            Slug = "velvet-tuxedo-suit",
                            Subcategory = "party-wear"
                        },
                        new
                        {
                            Id = "pw-004",
                            Badge = "Sale",
                            Description = "Smooth, lightweight satin shirt with an abstract floral print. Camp collar and relaxed fit make it the go-to shirt for rooftop parties and date nights. Available in sizes S-XXL.",
                            Image = "https://images.unsplash.com/photo-1603252109303-2751441dd157?w=600&h=700&fit=crop",
                            InStock = true,
                            Name = "Printed Satin Party Shirt",
                            OriginalPrice = 2499m,
                            Price = 1799m,
                            Rating = 4.4m,
                            ReviewCount = 678,
                            Slug = "printed-satin-party-shirt",
                            Subcategory = "party-wear"
                        },
                        new
                        {
                            Id = "pw-005",
                            Badge = "New",
                            Description = "Regal bandhgala suit with intricate thread embroidery on the collar and cuffs. Comes with matching straight trousers. Perfect for sangeet nights, cocktail parties, and wedding functions.",
                            Image = "https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=600&h=700&fit=crop",
                            InStock = true,
                            Name = "Embroidered Bandhgala Suit",
                            Price = 6499m,
                            Rating = 4.6m,
                            ReviewCount = 134,
                            Slug = "embroidered-bandhgala-suit",
                            Subcategory = "party-wear"
                        },
                        new
                        {
                            Id = "pw-006",
                            Description = "Head-turning co-ord set featuring a metallic gold shirt and matching slim-fit chinos. Effortlessly stylish for anniversary dinners, festival parties, and nightlife. Dry-clean recommended.",
                            Image = "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=600&h=700&fit=crop",
                            InStock = false,
                            Name = "Metallic Slim Chinos & Shirt Co-Ord",
                            OriginalPrice = 3799m,
                            Price = 2999m,
                            Rating = 4.3m,
                            ReviewCount = 290,
                            Slug = "metallic-slim-chinos-shirt-coord",
                            Subcategory = "party-wear"
                        },
                        new
                        {
                            Id = "ew-001",
                            Badge = "Sale",
                            Description = "Timeless white cotton kurta with subtle self-stripe texture. Breathable fabric keeps you comfortable during long pooja sessions or Eid celebrations. Comes with matching straight-cut pajama.",
                            Image = "https://images.unsplash.com/photo-1583391099995-d4adde10c1e4?w=600&h=700&fit=crop",
                            InStock = true,
                            Name = "Classic White Kurta Pajama",
                            OriginalPrice = 1799m,
                            Price = 1299m,
                            Rating = 4.6m,
                            ReviewCount = 1023,
                            Slug = "classic-white-kurta-pajama",
                            Subcategory = "ethnic-wear"
                        },
                        new
                        {
                            Id = "ew-002",
                            Badge = "Hot",
                            Description = "Resplendent ivory sherwani with gold zari embroidery throughout the yoke and cuffs. Includes churidar pants and a matching brocade dupatta. The ideal groom's look for wedding ceremonies.",
                            Image = "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=600&h=700&fit=crop",
                            InStock = true,
                            Name = "Royal Sherwani with Dupatta",
                            OriginalPrice = 14000m,
                            Price = 9999m,
                            Rating = 4.9m,
                            ReviewCount = 342,
                            Slug = "royal-sherwani-with-dupatta",
                            Subcategory = "ethnic-wear"
                        },
                        new
                        {
                            Id = "ew-003",
                            Badge = "New",
                            Description = "Breathable linen kurta in earthy terracotta with pintuck detailing on the placket. Paired with voluminous Patiala salwar -- a smart, breezy choice for summer festivals and cultural events.",
                            Image = "https://images.unsplash.com/photo-1612902456551-b67dd9fd54fc?w=600&h=700&fit=crop",
                            InStock = true,
                            Name = "Linen Kurta with Patiala Salwar",
                            Price = 1699m,
                            Rating = 4.5m,
                            ReviewCount = 567,
                            Slug = "linen-kurta-patiala-salwar",
                            Subcategory = "ethnic-wear"
                        },
                        new
                        {
                            Id = "ew-004",
                            Description = "Floor-length anarkali-style kurta for men in rich teal with block-printed borders. Flared silhouette with quarter sleeves. Comes with off-white straight-cut trousers for a balanced contrast.",
                            Image = "https://images.unsplash.com/photo-1607827448299-a099b845f076?w=600&h=700&fit=crop",
                            InStock = true,
                            Name = "Anarkali Kurta with Straight Pants",
                            OriginalPrice = 2999m,
                            Price = 2299m,
                            Rating = 4.4m,
                            ReviewCount = 215,
                            Slug = "anarkali-kurta-straight-pants",
                            Subcategory = "ethnic-wear"
                        },
                        new
                        {
                            Id = "ew-005",
                            Badge = "Sale",
                            Description = "Vibrant Bandhani (tie-dye) print kurta in cotton cambric fabric. The bright polka-dot resist-dye pattern celebrates Rajasthani craft. A go-to pick for Navratri, Holi, and cultural programs.",
                            Image = "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600&h=700&fit=crop",
                            InStock = true,
                            Name = "Bandhani Print Kurta",
                            OriginalPrice = 1499m,
                            Price = 999m,
                            Rating = 4.3m,
                            ReviewCount = 892,
                            Slug = "bandhani-print-kurta",
                            Subcategory = "ethnic-wear"
                        },
                        new
                        {
                            Id = "ew-006",
                            Description = "Ruggedly handsome Pathani salwar kameez in olive-green cotton-linen blend. Mandarin collar, full sleeves, and deep side slits offer movement and comfort. Pair with mojris for a complete traditional look.",
                            Image = "https://images.unsplash.com/photo-1620912189866-c4cf63048e63?w=600&h=700&fit=crop",
                            InStock = true,
                            Name = "Pathani Suit -- Olive Green",
                            Price = 1849m,
                            Rating = 4.7m,
                            ReviewCount = 441,
                            Slug = "pathani-suit-olive-green",
                            Subcategory = "ethnic-wear"
                        },
                        new
                        {
                            Id = "fm-001",
                            Badge = "Sale",
                            Description = "100% Egyptian cotton with a 2-ply weave for exceptional breathability and a smooth drape. French placket, barrel cuffs, and a slim fit through the chest and waist. Wrinkle-resistant -- perfect for long office days.",
                            Image = "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=700&fit=crop",
                            InStock = true,
                            Name = "Egyptian Cotton Dress Shirt -- White",
                            OriginalPrice = 1999m,
                            Price = 1499m,
                            Rating = 4.7m,
                            ReviewCount = 2134,
                            Slug = "egyptian-cotton-dress-shirt-white",
                            Subcategory = "formal"
                        },
                        new
                        {
                            Id = "fm-002",
                            Description = "Italian-inspired slim-fit trousers in a lightweight charcoal wool blend. Mid-rise waist, slash pockets, and a flat front give a polished, contemporary silhouette. Machine washable at 30C.",
                            Image = "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=600&h=700&fit=crop",
                            InStock = true,
                            Name = "Slim-Fit Wool Blend Trousers",
                            OriginalPrice = 2999m,
                            Price = 2199m,
                            Rating = 4.5m,
                            ReviewCount = 987,
                            Slug = "slim-fit-wool-blend-trousers",
                            Subcategory = "formal"
                        },
                        new
                        {
                            Id = "fm-003",
                            Badge = "New",
                            Description = "Classic alternating-stripe Oxford cloth shirt in navy and white. Button-down collar holds its shape without a tie pin. Relaxed fit gives room through the shoulders for comfortable, all-day wear.",
                            Image = "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600&h=700&fit=crop",
                            InStock = true,
                            Name = "Oxford Striped Business Shirt",
                            Price = 1249m,
                            Rating = 4.4m,
                            ReviewCount = 1456,
                            Slug = "oxford-striped-business-shirt",
                            Subcategory = "formal"
                        },
                        new
                        {
                            Id = "fm-004",
                            Badge = "Sale",
                            Description = "Elevate any formal look with this microfibre silk-blend tie in midnight blue paired with a matching white pocket square. Pre-tied option available. Ideal corporate gift for new joiners.",
                            Image = "https://images.unsplash.com/photo-1598522325074-042db73aa4e6?w=600&h=700&fit=crop",
                            InStock = true,
                            Name = "Formal Tie & Pocket Square Set",
                            OriginalPrice = 1199m,
                            Price = 799m,
                            Rating = 4.6m,
                            ReviewCount = 734,
                            Slug = "formal-tie-pocket-square-set",
                            Subcategory = "formal"
                        },
                        new
                        {
                            Id = "fm-005",
                            Badge = "Hot",
                            Description = "Heritage glen-plaid blazer in grey and navy. Structured shoulders, notch lapels, and a two-button single-breast closure. The perfect blazer to wear over a dress shirt for boardroom meetings.",
                            Image = "https://images.unsplash.com/photo-1549062572-544a64fb0c56?w=600&h=700&fit=crop",
                            InStock = true,
                            Name = "Checked Formal Blazer",
                            OriginalPrice = 5499m,
                            Price = 3999m,
                            Rating = 4.8m,
                            ReviewCount = 523,
                            Slug = "checked-formal-blazer",
                            Subcategory = "formal"
                        },
                        new
                        {
                            Id = "fm-006",
                            Description = "Genuine leather derby shoes with a cap toe and Goodyear welt construction. Cushioned insole for all-day comfort. Pairs flawlessly with trousers and formal suits for office or client meetings.",
                            Image = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=700&fit=crop",
                            InStock = false,
                            Name = "Formal Derby Shoes -- Black",
                            OriginalPrice = 3499m,
                            Price = 2799m,
                            Rating = 4.5m,
                            ReviewCount = 612,
                            Slug = "formal-derby-shoes-black",
                            Subcategory = "formal"
                        },
                        new
                        {
                            Id = "cs-001",
                            Description = "180 GSM combed cotton jersey tee with a reinforced crew neck that keeps its shape wash after wash. Pre-shrunk and available in 12 colours. The everyday staple that works under flannels or solo.",
                            Image = "https://images.unsplash.com/photo-1552374196-c4e7ffc6e126?w=600&h=700&fit=crop",
                            InStock = true,
                            Name = "Classic Fit Crew-Neck Tee",
                            Price = 499m,
                            Rating = 4.6m,
                            ReviewCount = 3412,
                            Slug = "classic-fit-crew-neck-tee",
                            Subcategory = "casual"
                        },
                        new
                        {
                            Id = "cs-002",
                            Badge = "Sale",
                            Description = "Four-way stretch denim with 2% elastane for unrestricted movement. Slim leg, mid-rise, with classic five-pocket construction. Fade-resistant indigo wash that gets better with every wear.",
                            Image = "https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&h=700&fit=crop",
                            InStock = true,
                            Name = "Slim Stretch Jeans -- Indigo",
                            OriginalPrice = 2299m,
                            Price = 1799m,
                            Rating = 4.5m,
                            ReviewCount = 2876,
                            Slug = "slim-stretch-jeans-indigo",
                            Subcategory = "casual"
                        },
                        new
                        {
                            Id = "cs-003",
                            Badge = "New",
                            Description = "Soft-brushed cotton flannel in a warm red plaid. Oversized silhouette is great as a layering shirt over tees or worn open like a jacket. Drop shoulders and chest pockets complete the look.",
                            Image = "https://images.unsplash.com/photo-1512138664757-360e0aad5132?w=600&h=700&fit=crop",
                            InStock = true,
                            Name = "Oversized Flannel Shirt",
                            Price = 1299m,
                            Rating = 4.7m,
                            ReviewCount = 1234,
                            Slug = "oversized-flannel-shirt",
                            Subcategory = "casual"
                        },
                        new
                        {
                            Id = "cs-004",
                            Description = "Relaxed-fit cargo shorts in durable olive ripstop cotton. Six pockets (including thigh cargo pockets) give you plenty of carry space. Elasticated waistband with a drawstring -- ideal for weekends and travel.",
                            Image = "https://images.unsplash.com/photo-1591195853828-11db59a44f43?w=600&h=700&fit=crop",
                            InStock = true,
                            Name = "Cargo Shorts -- Olive",
                            OriginalPrice = 1399m,
                            Price = 999m,
                            Rating = 4.4m,
                            ReviewCount = 1789,
                            Slug = "cargo-shorts-olive",
                            Subcategory = "casual"
                        },
                        new
                        {
                            Id = "cs-005",
                            Badge = "Hot",
                            Description = "320 GSM fleece-lined hoodie with a full-length YKK zip and kangaroo pocket. Ribbed cuffs and hem lock in warmth. The go-to throw-on for morning gym sessions, college campuses, and chill evenings.",
                            Image = "https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=600&h=700&fit=crop",
                            InStock = true,
                            Name = "Zip-Up Hoodie -- Charcoal",
                            OriginalPrice = 1999m,
                            Price = 1599m,
                            Rating = 4.8m,
                            ReviewCount = 2201,
                            Slug = "zip-up-hoodie-charcoal",
                            Subcategory = "casual"
                        },
                        new
                        {
                            Id = "cs-006",
                            Description = "Airy 100% linen trousers with an elasticated drawstring waist and tapered ankle. The natural fibre breathes beautifully -- perfect for hot days, beach trips, and relaxed cafe mornings.",
                            Image = "https://images.unsplash.com/photo-1506634572416-48cdfe9e6b6f?w=600&h=700&fit=crop",
                            InStock = true,
                            Name = "Linen Drawstring Trousers",
                            Price = 1149m,
                            Rating = 4.3m,
                            ReviewCount = 845,
                            Slug = "linen-drawstring-trousers",
                            Subcategory = "casual"
                        },
                        new
                        {
                            Id = "bs-001",
                            Badge = "Hot",
                            Description = "Impeccably tailored two-piece suit in super-120 navy wool. Slim fit with notch lapels, a single-breasted two-button closure, and a half canvas construction for natural drape. Includes matching flat-front trousers.",
                            Image = "https://images.unsplash.com/photo-1617127365659-c47fa9d30294?w=600&h=700&fit=crop",
                            InStock = true,
                            Name = "Slim-Fit 2-Piece Navy Suit",
                            OriginalPrice = 13500m,
                            Price = 9999m,
                            Rating = 4.9m,
                            ReviewCount = 678,
                            Slug = "slim-fit-2-piece-navy-suit",
                            Subcategory = "blazer-suits"
                        },
                        new
                        {
                            Id = "bs-002",
                            Badge = "Sale",
                            Description = "Sophisticated charcoal suit with a subtle white windowpane check pattern woven in Italian wool. Modern slim cut, double-vented jacket, and tapered trousers. A versatile power suit for executives and groomsmen alike.",
                            Image = "https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?w=600&h=700&fit=crop",
                            InStock = true,
                            Name = "Charcoal Windowpane Check Suit",
                            OriginalPrice = 15000m,
                            Price = 11499m,
                            Rating = 4.8m,
                            ReviewCount = 312,
                            Slug = "charcoal-windowpane-check-suit",
                            Subcategory = "blazer-suits"
                        },
                        new
                        {
                            Id = "bs-003",
                            Badge = "New",
                            Description = "Lightweight unstructured blazer in a breathable cotton-linen blend. No shoulder padding means a relaxed, easy fit -- dress it up with chinos or down with jeans. Available in off-white and khaki.",
                            Image = "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&h=700&fit=crop",
                            InStock = true,
                            Name = "Smart Casual Unstructured Blazer",
                            Price = 4499m,
                            Rating = 4.6m,
                            ReviewCount = 891,
                            Slug = "smart-casual-unstructured-blazer",
                            Subcategory = "blazer-suits"
                        },
                        new
                        {
                            Id = "bs-004",
                            Badge = "Premium",
                            Description = "Bold double-breasted suit in classic chalk-stripe navy flannel. Peak lapels, six-button front (fastened on two), and ticket pocket add old-school elegance. For the man who dresses to impress.",
                            Image = "https://images.unsplash.com/photo-1598032895397-b9472444bf93?w=600&h=700&fit=crop",
                            InStock = true,
                            Name = "Double-Breasted Pinstripe Suit",
                            OriginalPrice = 18000m,
                            Price = 13999m,
                            Rating = 4.9m,
                            ReviewCount = 145,
                            Slug = "double-breasted-pinstripe-suit",
                            Subcategory = "blazer-suits"
                        },
                        new
                        {
                            Id = "bs-005",
                            Description = "Versatile olive-green blazer cut from a wrinkle-resistant stretch wool blend. Four-way stretch fabric allows for full range of motion. Dress it over a turtleneck or wear solo over dark jeans for weekend events.",
                            Image = "https://images.unsplash.com/photo-1609957372782-aa0ab2f8eed8?w=600&h=700&fit=crop",
                            InStock = true,
                            Name = "Olive Green Stretch Blazer",
                            OriginalPrice = 4999m,
                            Price = 3799m,
                            Rating = 4.5m,
                            ReviewCount = 567,
                            Slug = "olive-green-stretch-blazer",
                            Subcategory = "blazer-suits"
                        },
                        new
                        {
                            Id = "bs-006",
                            Badge = "Sale",
                            Description = "Complete ivory three-piece suit -- jacket, waistcoat, and trousers -- in premium Italian wool-silk blend. Slim lapels with a contrast ivory satin and mother-of-pearl buttons. The dream groom or cocktail suit.",
                            Image = "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=600&h=700&fit=crop",
                            InStock = true,
                            Name = "3-Piece Wedding Suit -- Ivory",
                            OriginalPrice = 22000m,
                            Price = 16999m,
                            Rating = 4.9m,
                            ReviewCount = 98,
                            Slug = "3-piece-wedding-suit-ivory",
                            Subcategory = "blazer-suits"
                        },
                        new
                        {
                            Id = "fk-001",
                            Badge = "Hot",
                            Description = "Hand-dyed spiral tie-dye tee in electric blue and lime green. 240 GSM heavyweight cotton with a boxy, oversized drop-shoulder cut. Each piece is uniquely dyed -- no two are exactly alike. #OOTD guaranteed.",
                            Image = "https://images.unsplash.com/photo-1523398002811-999ca8dec234?w=600&h=700&fit=crop",
                            InStock = true,
                            Name = "Tie-Dye Oversized Tee",
                            Price = 699m,
                            Rating = 4.6m,
                            ReviewCount = 2345,
                            Slug = "tie-dye-oversized-tee",
                            Subcategory = "funky"
                        },
                        new
                        {
                            Id = "fk-002",
                            Badge = "Sale",
                            Description = "Y2K-inspired cargo pants featuring a multi-panel patchwork of contrasting fabrics and colours. Low-rise waist, wide-leg silhouette, and six utility pockets. The street-style statement piece that breaks all the rules.",
                            Image = "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&h=700&fit=crop",
                            InStock = true,
                            Name = "Patchwork Cargo Pants",
                            OriginalPrice = 2999m,
                            Price = 2199m,
                            Rating = 4.5m,
                            ReviewCount = 1123,
                            Slug = "patchwork-cargo-pants",
                            Subcategory = "funky"
                        },
                        new
                        {
                            Id = "fk-003",
                            Badge = "New",
                            Description = "Nylon bomber jacket with an all-over urban graffiti print. Ribbed collar, cuffs, and hem with a clean-zip front. Lightweight and windproof -- the perfect throw-on for festivals, skate parks, and late-night outings.",
                            Image = "https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?w=600&h=700&fit=crop",
                            InStock = true,
                            Name = "Graffiti Print Bomber Jacket",
                            OriginalPrice = 4499m,
                            Price = 3499m,
                            Rating = 4.8m,
                            ReviewCount = 876,
                            Slug = "graffiti-print-bomber-jacket",
                            Subcategory = "funky"
                        },
                        new
                        {
                            Id = "fk-004",
                            Description = "Black-and-white checkerboard co-ord set: an oversized short-sleeve shirt and matching wide-leg shorts. 90s skater aesthetic meets modern streetwear. Wear the full set or mix individually for infinite looks.",
                            Image = "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600&h=700&fit=crop",
                            InStock = true,
                            Name = "Checkerboard Vans-Style Co-Ord",
                            OriginalPrice = 3499m,
                            Price = 2799m,
                            Rating = 4.4m,
                            ReviewCount = 654,
                            Slug = "checkerboard-coord-set",
                            Subcategory = "funky"
                        },
                        new
                        {
                            Id = "fk-005",
                            Description = "Semi-transparent neon-green mesh top designed for layering over coloured tees or bralettes. Dropped shoulders, relaxed crew neck, and ribbed hem. Bold, boundary-pushing festival-wear for the unapologetically loud.",
                            Image = "https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=600&h=700&fit=crop",
                            InStock = true,
                            Name = "Neon Mesh Layering Top",
                            Price = 799m,
                            Rating = 4.2m,
                            ReviewCount = 432,
                            Slug = "neon-mesh-layering-top",
                            Subcategory = "funky"
                        },
                        new
                        {
                            Id = "fk-006",
                            Badge = "Hot",
                            Description = "Soft cotton-terry joggers covered in retro cartoon characters from the 90s. Elasticated waistband with drawstring, cuffed ankles, and deep side pockets. Cosy, fun, and wildly shareable on social media.",
                            Image = "https://images.unsplash.com/photo-1516762689617-e1cffcef479d?w=600&h=700&fit=crop",
                            InStock = true,
                            Name = "Cartoon Print Relaxed Joggers",
                            OriginalPrice = 1799m,
                            Price = 1399m,
                            Rating = 4.7m,
                            ReviewCount = 1543,
                            Slug = "cartoon-print-relaxed-joggers",
                            Subcategory = "funky"
                        });
                });

            modelBuilder.Entity("EcommerceLifestyle.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EcommerceLifestyle.DAL.Entities.Cart", b =>
                {
                    b.HasOne("EcommerceLifestyle.DAL.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcommerceLifestyle.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcommerceLifestyle.DAL.Entities.Inventory", b =>
                {
                    b.HasOne("EcommerceLifestyle.DAL.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcommerceLifestyle.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("EcommerceLifestyle.DAL.Entities.Order", b =>
                {
                    b.HasOne("EcommerceLifestyle.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcommerceLifestyle.DAL.Entities.OrderItem", b =>
                {
                    b.HasOne("EcommerceLifestyle.DAL.Entities.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcommerceLifestyle.DAL.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EcommerceLifestyle.DAL.Entities.Product", b =>
                {
                    b.HasOne("EcommerceLifestyle.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("EcommerceLifestyle.DAL.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
