using EcommerceLifestyle.DAL.Entities;
using EcommerceLifestyle.DAL.Entities.Enums;

namespace EcommerceLifestyle.DAL.Persistence;

// Seed catalogue translated 1:1 from
// e-commerce-lifestyle-frontend/src/features/men/data/menProducts.js
// VendorId is null because these were imported, not vendor-uploaded.
// EF Core HasData() will INSERT these on database creation / migration.
public static class SeedData
{
    public static readonly Product[] Products = new[]
    {
        // ── Party Wear ────────────────────────────────────────────────
        new Product { Id = "pw-001", Name = "Midnight Sequin Blazer", Slug = "midnight-sequin-blazer", Subcategory = "party-wear", Price = 3499m, OriginalPrice = 4999m, Rating = 4.7m, ReviewCount = 312, Badge = "Sale", Description = "Make a grand entrance with this midnight-black sequin blazer. Slim-fit cut with satin lapels, perfect for club nights and festive dinners. Pairs beautifully with black trousers or dark jeans.", Image = "https://images.unsplash.com/photo-1594938298603-c8148c4b4ae1?w=600&h=700&fit=crop", InStock = true },
        new Product { Id = "pw-002", Name = "Indo-Western Nehru Jacket Set", Slug = "indo-western-nehru-jacket-set", Subcategory = "party-wear", Price = 4199m, OriginalPrice = 5500m, Rating = 4.8m, ReviewCount = 489, Badge = "Hot", Description = "A stunning fusion of contemporary style and traditional Indian craftsmanship. Rich brocade Nehru jacket paired with slim churidar trousers. Ideal for cocktail parties, receptions, and festive occasions.", Image = "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&h=700&fit=crop", InStock = true },
        new Product { Id = "pw-003", Name = "Velvet Tuxedo Suit", Slug = "velvet-tuxedo-suit", Subcategory = "party-wear", Price = 8999m, OriginalPrice = 12000m, Rating = 4.9m, ReviewCount = 201, Badge = "Premium", Description = "Luxurious deep-burgundy velvet tuxedo that commands attention. Shawl lapel design with satin trim and matching trousers. The ultimate choice for gala dinners and black-tie events.", Image = "https://images.unsplash.com/photo-1617127365659-c47fa9d30294?w=600&h=700&fit=crop", InStock = true },
        new Product { Id = "pw-004", Name = "Printed Satin Party Shirt", Slug = "printed-satin-party-shirt", Subcategory = "party-wear", Price = 1799m, OriginalPrice = 2499m, Rating = 4.4m, ReviewCount = 678, Badge = "Sale", Description = "Smooth, lightweight satin shirt with an abstract floral print. Camp collar and relaxed fit make it the go-to shirt for rooftop parties and date nights. Available in sizes S-XXL.", Image = "https://images.unsplash.com/photo-1603252109303-2751441dd157?w=600&h=700&fit=crop", InStock = true },
        new Product { Id = "pw-005", Name = "Embroidered Bandhgala Suit", Slug = "embroidered-bandhgala-suit", Subcategory = "party-wear", Price = 6499m, OriginalPrice = null, Rating = 4.6m, ReviewCount = 134, Badge = "New", Description = "Regal bandhgala suit with intricate thread embroidery on the collar and cuffs. Comes with matching straight trousers. Perfect for sangeet nights, cocktail parties, and wedding functions.", Image = "https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=600&h=700&fit=crop", InStock = true },
        new Product { Id = "pw-006", Name = "Metallic Slim Chinos & Shirt Co-Ord", Slug = "metallic-slim-chinos-shirt-coord", Subcategory = "party-wear", Price = 2999m, OriginalPrice = 3799m, Rating = 4.3m, ReviewCount = 290, Badge = null, Description = "Head-turning co-ord set featuring a metallic gold shirt and matching slim-fit chinos. Effortlessly stylish for anniversary dinners, festival parties, and nightlife. Dry-clean recommended.", Image = "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=600&h=700&fit=crop", InStock = false },

        // ── Ethnic Wear ───────────────────────────────────────────────
        new Product { Id = "ew-001", Name = "Classic White Kurta Pajama", Slug = "classic-white-kurta-pajama", Subcategory = "ethnic-wear", Price = 1299m, OriginalPrice = 1799m, Rating = 4.6m, ReviewCount = 1023, Badge = "Sale", Description = "Timeless white cotton kurta with subtle self-stripe texture. Breathable fabric keeps you comfortable during long pooja sessions or Eid celebrations. Comes with matching straight-cut pajama.", Image = "https://images.unsplash.com/photo-1583391099995-d4adde10c1e4?w=600&h=700&fit=crop", InStock = true },
        new Product { Id = "ew-002", Name = "Royal Sherwani with Dupatta", Slug = "royal-sherwani-with-dupatta", Subcategory = "ethnic-wear", Price = 9999m, OriginalPrice = 14000m, Rating = 4.9m, ReviewCount = 342, Badge = "Hot", Description = "Resplendent ivory sherwani with gold zari embroidery throughout the yoke and cuffs. Includes churidar pants and a matching brocade dupatta. The ideal groom's look for wedding ceremonies.", Image = "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=600&h=700&fit=crop", InStock = true },
        new Product { Id = "ew-003", Name = "Linen Kurta with Patiala Salwar", Slug = "linen-kurta-patiala-salwar", Subcategory = "ethnic-wear", Price = 1699m, OriginalPrice = null, Rating = 4.5m, ReviewCount = 567, Badge = "New", Description = "Breathable linen kurta in earthy terracotta with pintuck detailing on the placket. Paired with voluminous Patiala salwar -- a smart, breezy choice for summer festivals and cultural events.", Image = "https://images.unsplash.com/photo-1612902456551-b67dd9fd54fc?w=600&h=700&fit=crop", InStock = true },
        new Product { Id = "ew-004", Name = "Anarkali Kurta with Straight Pants", Slug = "anarkali-kurta-straight-pants", Subcategory = "ethnic-wear", Price = 2299m, OriginalPrice = 2999m, Rating = 4.4m, ReviewCount = 215, Badge = null, Description = "Floor-length anarkali-style kurta for men in rich teal with block-printed borders. Flared silhouette with quarter sleeves. Comes with off-white straight-cut trousers for a balanced contrast.", Image = "https://images.unsplash.com/photo-1607827448299-a099b845f076?w=600&h=700&fit=crop", InStock = true },
        new Product { Id = "ew-005", Name = "Bandhani Print Kurta", Slug = "bandhani-print-kurta", Subcategory = "ethnic-wear", Price = 999m, OriginalPrice = 1499m, Rating = 4.3m, ReviewCount = 892, Badge = "Sale", Description = "Vibrant Bandhani (tie-dye) print kurta in cotton cambric fabric. The bright polka-dot resist-dye pattern celebrates Rajasthani craft. A go-to pick for Navratri, Holi, and cultural programs.", Image = "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600&h=700&fit=crop", InStock = true },
        new Product { Id = "ew-006", Name = "Pathani Suit -- Olive Green", Slug = "pathani-suit-olive-green", Subcategory = "ethnic-wear", Price = 1849m, OriginalPrice = null, Rating = 4.7m, ReviewCount = 441, Badge = null, Description = "Ruggedly handsome Pathani salwar kameez in olive-green cotton-linen blend. Mandarin collar, full sleeves, and deep side slits offer movement and comfort. Pair with mojris for a complete traditional look.", Image = "https://images.unsplash.com/photo-1620912189866-c4cf63048e63?w=600&h=700&fit=crop", InStock = true },

        // ── Formal ────────────────────────────────────────────────────
        new Product { Id = "fm-001", Name = "Egyptian Cotton Dress Shirt -- White", Slug = "egyptian-cotton-dress-shirt-white", Subcategory = "formal", Price = 1499m, OriginalPrice = 1999m, Rating = 4.7m, ReviewCount = 2134, Badge = "Sale", Description = "100% Egyptian cotton with a 2-ply weave for exceptional breathability and a smooth drape. French placket, barrel cuffs, and a slim fit through the chest and waist. Wrinkle-resistant -- perfect for long office days.", Image = "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=700&fit=crop", InStock = true },
        new Product { Id = "fm-002", Name = "Slim-Fit Wool Blend Trousers", Slug = "slim-fit-wool-blend-trousers", Subcategory = "formal", Price = 2199m, OriginalPrice = 2999m, Rating = 4.5m, ReviewCount = 987, Badge = null, Description = "Italian-inspired slim-fit trousers in a lightweight charcoal wool blend. Mid-rise waist, slash pockets, and a flat front give a polished, contemporary silhouette. Machine washable at 30C.", Image = "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=600&h=700&fit=crop", InStock = true },
        new Product { Id = "fm-003", Name = "Oxford Striped Business Shirt", Slug = "oxford-striped-business-shirt", Subcategory = "formal", Price = 1249m, OriginalPrice = null, Rating = 4.4m, ReviewCount = 1456, Badge = "New", Description = "Classic alternating-stripe Oxford cloth shirt in navy and white. Button-down collar holds its shape without a tie pin. Relaxed fit gives room through the shoulders for comfortable, all-day wear.", Image = "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600&h=700&fit=crop", InStock = true },
        new Product { Id = "fm-004", Name = "Formal Tie & Pocket Square Set", Slug = "formal-tie-pocket-square-set", Subcategory = "formal", Price = 799m, OriginalPrice = 1199m, Rating = 4.6m, ReviewCount = 734, Badge = "Sale", Description = "Elevate any formal look with this microfibre silk-blend tie in midnight blue paired with a matching white pocket square. Pre-tied option available. Ideal corporate gift for new joiners.", Image = "https://images.unsplash.com/photo-1598522325074-042db73aa4e6?w=600&h=700&fit=crop", InStock = true },
        new Product { Id = "fm-005", Name = "Checked Formal Blazer", Slug = "checked-formal-blazer", Subcategory = "formal", Price = 3999m, OriginalPrice = 5499m, Rating = 4.8m, ReviewCount = 523, Badge = "Hot", Description = "Heritage glen-plaid blazer in grey and navy. Structured shoulders, notch lapels, and a two-button single-breast closure. The perfect blazer to wear over a dress shirt for boardroom meetings.", Image = "https://images.unsplash.com/photo-1549062572-544a64fb0c56?w=600&h=700&fit=crop", InStock = true },
        new Product { Id = "fm-006", Name = "Formal Derby Shoes -- Black", Slug = "formal-derby-shoes-black", Subcategory = "formal", Price = 2799m, OriginalPrice = 3499m, Rating = 4.5m, ReviewCount = 612, Badge = null, Description = "Genuine leather derby shoes with a cap toe and Goodyear welt construction. Cushioned insole for all-day comfort. Pairs flawlessly with trousers and formal suits for office or client meetings.", Image = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=700&fit=crop", InStock = false },

        // ── Casual ────────────────────────────────────────────────────
        new Product { Id = "cs-001", Name = "Classic Fit Crew-Neck Tee", Slug = "classic-fit-crew-neck-tee", Subcategory = "casual", Price = 499m, OriginalPrice = null, Rating = 4.6m, ReviewCount = 3412, Badge = null, Description = "180 GSM combed cotton jersey tee with a reinforced crew neck that keeps its shape wash after wash. Pre-shrunk and available in 12 colours. The everyday staple that works under flannels or solo.", Image = "https://images.unsplash.com/photo-1552374196-c4e7ffc6e126?w=600&h=700&fit=crop", InStock = true },
        new Product { Id = "cs-002", Name = "Slim Stretch Jeans -- Indigo", Slug = "slim-stretch-jeans-indigo", Subcategory = "casual", Price = 1799m, OriginalPrice = 2299m, Rating = 4.5m, ReviewCount = 2876, Badge = "Sale", Description = "Four-way stretch denim with 2% elastane for unrestricted movement. Slim leg, mid-rise, with classic five-pocket construction. Fade-resistant indigo wash that gets better with every wear.", Image = "https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&h=700&fit=crop", InStock = true },
        new Product { Id = "cs-003", Name = "Oversized Flannel Shirt", Slug = "oversized-flannel-shirt", Subcategory = "casual", Price = 1299m, OriginalPrice = null, Rating = 4.7m, ReviewCount = 1234, Badge = "New", Description = "Soft-brushed cotton flannel in a warm red plaid. Oversized silhouette is great as a layering shirt over tees or worn open like a jacket. Drop shoulders and chest pockets complete the look.", Image = "https://images.unsplash.com/photo-1512138664757-360e0aad5132?w=600&h=700&fit=crop", InStock = true },
        new Product { Id = "cs-004", Name = "Cargo Shorts -- Olive", Slug = "cargo-shorts-olive", Subcategory = "casual", Price = 999m, OriginalPrice = 1399m, Rating = 4.4m, ReviewCount = 1789, Badge = null, Description = "Relaxed-fit cargo shorts in durable olive ripstop cotton. Six pockets (including thigh cargo pockets) give you plenty of carry space. Elasticated waistband with a drawstring -- ideal for weekends and travel.", Image = "https://images.unsplash.com/photo-1591195853828-11db59a44f43?w=600&h=700&fit=crop", InStock = true },
        new Product { Id = "cs-005", Name = "Zip-Up Hoodie -- Charcoal", Slug = "zip-up-hoodie-charcoal", Subcategory = "casual", Price = 1599m, OriginalPrice = 1999m, Rating = 4.8m, ReviewCount = 2201, Badge = "Hot", Description = "320 GSM fleece-lined hoodie with a full-length YKK zip and kangaroo pocket. Ribbed cuffs and hem lock in warmth. The go-to throw-on for morning gym sessions, college campuses, and chill evenings.", Image = "https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=600&h=700&fit=crop", InStock = true },
        new Product { Id = "cs-006", Name = "Linen Drawstring Trousers", Slug = "linen-drawstring-trousers", Subcategory = "casual", Price = 1149m, OriginalPrice = null, Rating = 4.3m, ReviewCount = 845, Badge = null, Description = "Airy 100% linen trousers with an elasticated drawstring waist and tapered ankle. The natural fibre breathes beautifully -- perfect for hot days, beach trips, and relaxed cafe mornings.", Image = "https://images.unsplash.com/photo-1506634572416-48cdfe9e6b6f?w=600&h=700&fit=crop", InStock = true },

        // ── Blazer & Suits ────────────────────────────────────────────
        new Product { Id = "bs-001", Name = "Slim-Fit 2-Piece Navy Suit", Slug = "slim-fit-2-piece-navy-suit", Subcategory = "blazer-suits", Price = 9999m, OriginalPrice = 13500m, Rating = 4.9m, ReviewCount = 678, Badge = "Hot", Description = "Impeccably tailored two-piece suit in super-120 navy wool. Slim fit with notch lapels, a single-breasted two-button closure, and a half canvas construction for natural drape. Includes matching flat-front trousers.", Image = "https://images.unsplash.com/photo-1617127365659-c47fa9d30294?w=600&h=700&fit=crop", InStock = true },
        new Product { Id = "bs-002", Name = "Charcoal Windowpane Check Suit", Slug = "charcoal-windowpane-check-suit", Subcategory = "blazer-suits", Price = 11499m, OriginalPrice = 15000m, Rating = 4.8m, ReviewCount = 312, Badge = "Sale", Description = "Sophisticated charcoal suit with a subtle white windowpane check pattern woven in Italian wool. Modern slim cut, double-vented jacket, and tapered trousers. A versatile power suit for executives and groomsmen alike.", Image = "https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?w=600&h=700&fit=crop", InStock = true },
        new Product { Id = "bs-003", Name = "Smart Casual Unstructured Blazer", Slug = "smart-casual-unstructured-blazer", Subcategory = "blazer-suits", Price = 4499m, OriginalPrice = null, Rating = 4.6m, ReviewCount = 891, Badge = "New", Description = "Lightweight unstructured blazer in a breathable cotton-linen blend. No shoulder padding means a relaxed, easy fit -- dress it up with chinos or down with jeans. Available in off-white and khaki.", Image = "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&h=700&fit=crop", InStock = true },
        new Product { Id = "bs-004", Name = "Double-Breasted Pinstripe Suit", Slug = "double-breasted-pinstripe-suit", Subcategory = "blazer-suits", Price = 13999m, OriginalPrice = 18000m, Rating = 4.9m, ReviewCount = 145, Badge = "Premium", Description = "Bold double-breasted suit in classic chalk-stripe navy flannel. Peak lapels, six-button front (fastened on two), and ticket pocket add old-school elegance. For the man who dresses to impress.", Image = "https://images.unsplash.com/photo-1598032895397-b9472444bf93?w=600&h=700&fit=crop", InStock = true },
        new Product { Id = "bs-005", Name = "Olive Green Stretch Blazer", Slug = "olive-green-stretch-blazer", Subcategory = "blazer-suits", Price = 3799m, OriginalPrice = 4999m, Rating = 4.5m, ReviewCount = 567, Badge = null, Description = "Versatile olive-green blazer cut from a wrinkle-resistant stretch wool blend. Four-way stretch fabric allows for full range of motion. Dress it over a turtleneck or wear solo over dark jeans for weekend events.", Image = "https://images.unsplash.com/photo-1609957372782-aa0ab2f8eed8?w=600&h=700&fit=crop", InStock = true },
        new Product { Id = "bs-006", Name = "3-Piece Wedding Suit -- Ivory", Slug = "3-piece-wedding-suit-ivory", Subcategory = "blazer-suits", Price = 16999m, OriginalPrice = 22000m, Rating = 4.9m, ReviewCount = 98, Badge = "Sale", Description = "Complete ivory three-piece suit -- jacket, waistcoat, and trousers -- in premium Italian wool-silk blend. Slim lapels with a contrast ivory satin and mother-of-pearl buttons. The dream groom or cocktail suit.", Image = "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=600&h=700&fit=crop", InStock = true },

        // ── Funky ─────────────────────────────────────────────────────
        new Product { Id = "fk-001", Name = "Tie-Dye Oversized Tee", Slug = "tie-dye-oversized-tee", Subcategory = "funky", Price = 699m, OriginalPrice = null, Rating = 4.6m, ReviewCount = 2345, Badge = "Hot", Description = "Hand-dyed spiral tie-dye tee in electric blue and lime green. 240 GSM heavyweight cotton with a boxy, oversized drop-shoulder cut. Each piece is uniquely dyed -- no two are exactly alike. #OOTD guaranteed.", Image = "https://images.unsplash.com/photo-1523398002811-999ca8dec234?w=600&h=700&fit=crop", InStock = true },
        new Product { Id = "fk-002", Name = "Patchwork Cargo Pants", Slug = "patchwork-cargo-pants", Subcategory = "funky", Price = 2199m, OriginalPrice = 2999m, Rating = 4.5m, ReviewCount = 1123, Badge = "Sale", Description = "Y2K-inspired cargo pants featuring a multi-panel patchwork of contrasting fabrics and colours. Low-rise waist, wide-leg silhouette, and six utility pockets. The street-style statement piece that breaks all the rules.", Image = "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&h=700&fit=crop", InStock = true },
        new Product { Id = "fk-003", Name = "Graffiti Print Bomber Jacket", Slug = "graffiti-print-bomber-jacket", Subcategory = "funky", Price = 3499m, OriginalPrice = 4499m, Rating = 4.8m, ReviewCount = 876, Badge = "New", Description = "Nylon bomber jacket with an all-over urban graffiti print. Ribbed collar, cuffs, and hem with a clean-zip front. Lightweight and windproof -- the perfect throw-on for festivals, skate parks, and late-night outings.", Image = "https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?w=600&h=700&fit=crop", InStock = true },
        new Product { Id = "fk-004", Name = "Checkerboard Vans-Style Co-Ord", Slug = "checkerboard-coord-set", Subcategory = "funky", Price = 2799m, OriginalPrice = 3499m, Rating = 4.4m, ReviewCount = 654, Badge = null, Description = "Black-and-white checkerboard co-ord set: an oversized short-sleeve shirt and matching wide-leg shorts. 90s skater aesthetic meets modern streetwear. Wear the full set or mix individually for infinite looks.", Image = "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600&h=700&fit=crop", InStock = true },
        new Product { Id = "fk-005", Name = "Neon Mesh Layering Top", Slug = "neon-mesh-layering-top", Subcategory = "funky", Price = 799m, OriginalPrice = null, Rating = 4.2m, ReviewCount = 432, Badge = null, Description = "Semi-transparent neon-green mesh top designed for layering over coloured tees or bralettes. Dropped shoulders, relaxed crew neck, and ribbed hem. Bold, boundary-pushing festival-wear for the unapologetically loud.", Image = "https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=600&h=700&fit=crop", InStock = true },
        new Product { Id = "fk-006", Name = "Cartoon Print Relaxed Joggers", Slug = "cartoon-print-relaxed-joggers", Subcategory = "funky", Price = 1399m, OriginalPrice = 1799m, Rating = 4.7m, ReviewCount = 1543, Badge = "Hot", Description = "Soft cotton-terry joggers covered in retro cartoon characters from the 90s. Elasticated waistband with drawstring, cuffed ankles, and deep side pockets. Cosy, fun, and wildly shareable on social media.", Image = "https://images.unsplash.com/photo-1516762689617-e1cffcef479d?w=600&h=700&fit=crop", InStock = true },
    };

    // Static seed timestamp -- EF requires deterministic data for HasData (no DateTime.UtcNow).
    private static readonly DateTime SeedTimestamp = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc);

    // Five seed accounts for local development. Passwords are intentionally
    // simple ({firstname}123). BCrypt hashes are pre-computed because HasData
    // demands deterministic values -- a runtime call to BCrypt.HashPassword
    // would generate a fresh salt every build and EF would emit a new
    // migration each time. All hashes share the salt $2a$11$Mt5PNdur41SlBIGBosZy0u.
    //   afzal@example.com    -> "afzal123"     (User)
    //   abhishek@example.com -> "abhishek123"  (User)
    //   sudhir@example.com   -> "sudhir123"    (User)
    //   demo@example.com     -> "demo123"      (User)
    //   vendor@example.com   -> "vendor123"    (Vendor)
    public static readonly User[] Users = new[]
    {
        new User { Id = 1, FirstName = "Afzal",    LastName = "Haroon",  Email = "afzal@example.com",    PasswordHash = "$2a$11$Mt5PNdur41SlBIGBosZy0u1DeJ6z3avZ9ReGci5rG1.6mVUkg538C", Role = UserRole.User,   CreatedAt = SeedTimestamp, Provider = "Local" },
        new User { Id = 2, FirstName = "Abhishek", LastName = "Srivastava",   Email = "abhishek@example.com", PasswordHash = "$2a$11$Mt5PNdur41SlBIGBosZy0ukcVxRInybBi/HKtPOqJpA8z1xgnCtAy", Role = UserRole.User,   CreatedAt = SeedTimestamp, Provider = "Local" },
        new User { Id = 3, FirstName = "Sudhir",   LastName = "Panda",   Email = "sudhir@example.com",   PasswordHash = "$2a$11$Mt5PNdur41SlBIGBosZy0uKD2/EzPqUCAE8t6l/ho8T027wok0wD.", Role = UserRole.User,   CreatedAt = SeedTimestamp, Provider = "Local" },
        new User { Id = 4, FirstName = "Demo",     LastName = "User",    Email = "demo@example.com",     PasswordHash = "$2a$11$Mt5PNdur41SlBIGBosZy0uyGr/eADcK7Y4Y4iTfDxyXgVvvPRVJw6", Role = UserRole.User,   CreatedAt = SeedTimestamp, Provider = "Local" },
        new User { Id = 5, FirstName = "Vendor",   LastName = "Account", Email = "vendor@example.com",   PasswordHash = "$2a$11$Mt5PNdur41SlBIGBosZy0u.D3Al5BEyQsTng4LvhAOtvMs3DPTu62", Role = UserRole.Vendor, CreatedAt = SeedTimestamp, Provider = "Local" },
    };

    // One Inventory row per seeded product so vendor inventory endpoints
    // have data to query immediately. Auto-incremented ints starting at 1.
    public static readonly Inventory[] InventoryRows = BuildInventory();

    private static Inventory[] BuildInventory()
    {
        var rows = new Inventory[Products.Length];
        for (int i = 0; i < Products.Length; i++)
        {
            rows[i] = new Inventory
            {
                Id = i + 1,
                ProductId = Products[i].Id,
                QuantityAvailable = 50,
                ReorderLevel = 5,
                LastUpdated = SeedTimestamp,
                VendorId = null
            };
        }
        return rows;
    }
}
